/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CommunityMedical;

import Business.Enterprise.Enterprise;
import Business.Information.Disease;
import Business.Organization.Organization;
import Business.Organization.ResidenceOrganization;
import Business.Role.ResidenceRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicalWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cassiopeia
 */
public class MedicalWorkArea extends javax.swing.JPanel {

    private JPanel userContainerProcess;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private String welcome;

    /**
     * Creates new form MedicalWorkArea
     */
    public MedicalWorkArea(JPanel upc, Enterprise e, UserAccount ua) {
        initComponents();

        userAccount = ua;
        userContainerProcess = upc;
        enterprise = e;

        welcome = "This is Work Area For " + enterprise + " " + enterprise.getEnterpriseType().getValue() + " Admin";
        jLabelWelcome.setText(welcome);
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Warning");
        jComboBox1.addItem("Reminder");
        jComboBox1.addItem("Important");
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Respiratory diseases");

        populateCB3();
        populateDisTable();
    }

    public void populateCB3() {
        jComboBox3.removeAllItems();
        for (Organization og : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (og instanceof ResidenceOrganization) {
                for (UserAccount ust : og.getUserAccountDirectory().getUserAccountList()) {
                    jComboBox3.addItem(ust);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogOutBtn1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jOrzBtn = new javax.swing.JButton();
        jEmpBtn = new javax.swing.JButton();
        jUserBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSendToAllBtn = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();

        jLogOutBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLogOutBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/message-already-read-icon.png"))); // NOI18N
        jLogOutBtn1.setText("Message Box");
        jLogOutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutBtn1ActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Diseases");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Residence");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Diseases"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Create Diseases");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 123, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Work Area", jPanel1);

        jOrzBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOrzBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/people-icon.png"))); // NOI18N
        jOrzBtn.setText("Manage Organization");
        jOrzBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOrzBtnActionPerformed(evt);
            }
        });

        jEmpBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Preppy-icon.png"))); // NOI18N
        jEmpBtn.setText("Manage Residence");
        jEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpBtnActionPerformed(evt);
            }
        });

        jUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Office-Girl-icon.png"))); // NOI18N
        jUserBtn.setText("Manage User Account");
        jUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jOrzBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jOrzBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage User", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Message Type");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Content");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSendToAllBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSendToAllBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/people-icon.png"))); // NOI18N
        jSendToAllBtn.setText("Send To All Community");
        jSendToAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendToAllBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSendToAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSendToAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Send Message", jPanel2);

        jLabelWelcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(0, 204, 0));
        jLabelWelcome.setText("Welcome !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLogOutBtn1)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogOutBtn1)
                    .addComponent(jLabelWelcome))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLogOutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutBtn1ActionPerformed
        MessageBox manageEnterpriseJPanel = new MessageBox(userContainerProcess, enterprise.getUserAccountDirectory().getUserAccountList().get(0), enterprise);
        userContainerProcess.add("MessageBox", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userContainerProcess.getLayout();
        layout.next(userContainerProcess);
    }//GEN-LAST:event_jLogOutBtn1ActionPerformed

    private void jSendToAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendToAllBtnActionPerformed
        String message = jTextArea1.getText();
        MedicalWorkRequest request = new MedicalWorkRequest();
        request.setMessage(message);
        request.setMessageType(jComboBox1.getSelectedItem().toString());
        request.setSender(userAccount);
        request.setStatus("Sent");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof ResidenceOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Sent Successfully!");
        }
    }//GEN-LAST:event_jSendToAllBtnActionPerformed

    private void jOrzBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrzBtnActionPerformed
        ManageOrganizationJPanel manageEnterpriseJPanel = new ManageOrganizationJPanel(userContainerProcess, enterprise.getOrganizationDirectory());
        userContainerProcess.add("ManageOrganizationJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userContainerProcess.getLayout();
        layout.next(userContainerProcess);
    }//GEN-LAST:event_jOrzBtnActionPerformed

    private void jEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpBtnActionPerformed
        ManageEmployeeJPanel manageEnterpriseJPanel = new ManageEmployeeJPanel(userContainerProcess, enterprise.getOrganizationDirectory());
        userContainerProcess.add("ManageEmployeeJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userContainerProcess.getLayout();
        layout.next(userContainerProcess);
    }//GEN-LAST:event_jEmpBtnActionPerformed

    private void jUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserBtnActionPerformed

        ManageUserAccountJPanel manageEnterpriseJPanel = new ManageUserAccountJPanel(userContainerProcess, enterprise);
        userContainerProcess.add("ManageUserAccountJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userContainerProcess.getLayout();
        layout.next(userContainerProcess);
    }//GEN-LAST:event_jUserBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Disease disease = new Disease();
        disease.setNameDisease(jComboBox2.getSelectedItem().toString());
        UserAccount userAcco = (UserAccount) jComboBox3.getSelectedItem();
        ((ResidenceRole) userAcco.getRole()).getDiseaseDirectory().addDisease(disease);
        populateDisTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateDisTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
//(Business.Role.ResidenceRole) Business.Role.ResidenceRole
        for (Organization or : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (or instanceof ResidenceOrganization) {
                for (UserAccount usa : or.getUserAccountDirectory().getUserAccountList()) {
                    if (usa.getRole().toString().equals("Business.Role.ResidenceRole")) {
                        Object row[] = new Object[2];
                        row[0] = usa.getUsername();
                        for(Disease si: ((ResidenceRole)usa.getRole()).getDiseaseDirectory().getDiseaseList())
                            row[1] = si.getNameDisease();
                        ((DefaultTableModel) jTable1.getModel()).addRow(row);
                    }
                }
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JButton jEmpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JButton jLogOutBtn1;
    private javax.swing.JButton jOrzBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSendToAllBtn;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jUserBtn;
    // End of variables declaration//GEN-END:variables
}
