/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DiplomacyWorkArea;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.DiplomacyOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DiplomacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Cassiopeia
 */
public class DiplomacyWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DiplomacyOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;

    /**
     * Creates new form DiplomacyWorkArea
     */
    public DiplomacyWorkArea(JPanel userProcessContainer, UserAccount account, DiplomacyOrganization organization, Enterprise enterprise, Network net) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        network = net;
        populateReceiveTableA();
        populateSendTableA();
        TableColumn tc = jReceivedTab1.getTableHeader().getColumnModel().getColumn(3);
        tc.setMaxWidth(0);
        tc.setMinWidth(0);
        tc.setPreferredWidth(0);

        TableColumn ts = jSendTa1.getTableHeader().getColumnModel().getColumn(3);
        ts.setMaxWidth(0);
        ts.setMinWidth(0);
        ts.setPreferredWidth(0);

        jComboBox1.removeAllItems();
        jComboBox1.addItem("Warning");
        jComboBox1.addItem("Reminder");
        jComboBox1.addItem("Important");
        populateHos();
    }

    public void populateHos() {
        jComboBox2.removeAllItems();
        for (Enterprise enterpriseA : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterpriseA instanceof HospitalEnterprise) {
                if (enterpriseA.getUserAccountDirectory().getUserAccountList().size() != 0) {
                    jComboBox2.addItem(enterpriseA.getUserAccountDirectory().getUserAccountList().get(0));
                }
            }
        }
    }

    public void populateReceiveTableA() {
        DefaultTableModel model = (DefaultTableModel) jReceivedTab1.getModel();
        model.setRowCount(0);
        SimpleDateFormat ft = new SimpleDateFormat("MM-dd-yyyy");

        for (WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()) {
            if (wr.getReceiver() != null && wr.getReceiver().equals(userAccount)) {
                Object row[] = new Object[4];
                row[0] = wr.getSender();
                row[1] = ft.format(wr.getRequestDate());
                row[2] = wr.getMessageType();
                row[3] = wr.getMessage();
                ((DefaultTableModel) jReceivedTab1.getModel()).addRow(row);
            }
        }

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {

            Object row[] = new Object[4];
            row[0] = wr.getSender();
            row[1] = ft.format(wr.getRequestDate());
            row[2] = wr.getMessageType();
            row[3] = wr.getMessage();
            ((DefaultTableModel) jReceivedTab1.getModel()).addRow(row);
//            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
        }

    }

    public void populateSendTableA() {
        DefaultTableModel model = (DefaultTableModel) jSendTa1.getModel();
        model.setRowCount(0);
        SimpleDateFormat ft = new SimpleDateFormat("MM-dd-yyyy");

        for (WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()) {
            if (wr.getSender().equals(userAccount)) {
                Object row[] = new Object[4];
                if (wr.getReceiver() != null) {
                    row[0] = wr.getReceiver();
                } else {
                    row[0] = "All Diplomacy";
                }
                row[1] = ft.format(wr.getRequestDate());
                row[2] = wr.getMessageType();
                row[3] = wr.getMessage();
                ((DefaultTableModel) jSendTa1.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jSendOneButton = new javax.swing.JButton();
        jSendAllBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jReceivedTab1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jSendTa1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Message Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Send to");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSendOneButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSendOneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Preppy-icon.png"))); // NOI18N
        jSendOneButton.setText("Send");
        jSendOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendOneButtonActionPerformed(evt);
            }
        });

        jSendAllBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSendAllBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/people-icon.png"))); // NOI18N
        jSendAllBtn.setText("Send To All Hospital");
        jSendAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendAllBtnActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 667, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, 0, 203, Short.MAX_VALUE))
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSendOneButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSendAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSendOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSendAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Send Message", jPanel3);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jReceivedTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Date", "Type", "Title 4"
            }
        ));
        jReceivedTab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jReceivedTab1MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jReceivedTab1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Message Details");

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane9.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane3.addTab("Received Message", jPanel5);

        jSendTa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reciver", "Date", "Type", "Content"
            }
        ));
        jSendTa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSendTa1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jSendTa1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Message Details");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane7.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 488, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Sended Message", jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane2.addTab("Message Box", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSendTa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSendTa1MouseClicked

        int selectedRow = jSendTa1.getSelectedRow();
        String mes;
        mes = jSendTa1.getValueAt(selectedRow, 3).toString();
        if (selectedRow >= 0) {
            jTextArea4.setText(mes);
        }
    }//GEN-LAST:event_jSendTa1MouseClicked

    private void jReceivedTab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReceivedTab1MouseClicked
        int selectedRow = jReceivedTab1.getSelectedRow();
        String mes;
        mes = jReceivedTab1.getValueAt(selectedRow, 3).toString();
        if (selectedRow >= 0) {
            jTextArea5.setText(mes);
        }
    }//GEN-LAST:event_jReceivedTab1MouseClicked

    private void jSendAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendAllBtnActionPerformed
        String message = jTextArea3.getText();
        DiplomacyWorkRequest request = new DiplomacyWorkRequest();
        request.setMessage(message);
        request.setMessageType(jComboBox1.getSelectedItem().toString());
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        
        for (int i=0; i<jComboBox2.getItemCount();i++) {
            request.setReceiver((UserAccount) jComboBox2.getSelectedItem());
            UserAccount messageReceiver = (UserAccount) jComboBox2.getSelectedItem();
            messageReceiver.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Sent Successfully!");
        populateSendTableA();
        

//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//            if (organization instanceof DiplomacyOrganization) {
//                org = organization;
//                break;
//            }
//        }
//        if (org != null) {
//            org.getWorkQueue().getWorkRequestList().add(request);
//            userAccount.getWorkQueue().getWorkRequestList().add(request);
//            JOptionPane.showMessageDialog(null, "Sent Successfully!");
//        }
    }//GEN-LAST:event_jSendAllBtnActionPerformed

    private void jSendOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendOneButtonActionPerformed
        String message = jTextArea3.getText();
        DiplomacyWorkRequest request = new DiplomacyWorkRequest();
        request.setMessage(message);
        request.setMessageType(jComboBox1.getSelectedItem().toString());
        request.setSender(userAccount);
        request.setReceiver((UserAccount) jComboBox2.getSelectedItem());
        request.setStatus("Sent");

        UserAccount messageReceiver = (UserAccount) jComboBox2.getSelectedItem();
        messageReceiver.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Sent Successfully!");
        populateSendTableA();
    }//GEN-LAST:event_jSendOneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTable jReceivedTab1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jSendAllBtn;
    private javax.swing.JButton jSendOneButton;
    private javax.swing.JTable jSendTa1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
